### ISSUE TITLE
Duplicate products

### ISSUE THREAD

**Issue by jyourstone** [Mondido/MondidoWooCommerce#21]
The following code on rows 855-857 in index.php added in version 3.5 causes the duplicate product bug to appear again:

`                if(empty($items_item["artno"])){
                    $items_item["artno"] = $prod->id;
                    }`

This happens when an SKU has not been added in WooCommerce for a single product. A duplicate product will appear in the order after payment has been completed.

**Comment by robbanp** [comment]
Right! @jyourstone We'll look
