### ISSUE TITLE
Percentage discount causing transaction mismatch

### ISSUE THREAD

**Issue by jyourstone** [Mondido/MondidoWooCommerce#22]
When adding a percentage discount coupon code in WooCommerce and the total sum is in decimals (for instance 203.50), when paying Mondidi will throw a transaction mismatch error, at least when choosing invoice as payment. 

This happens even if you have set WooCommerce to use two decimals.

**Comment by jyourstone** [comment]
Actually it seems that no discounts work. I just tried adding a discount for 10 SEK but that also threw a transaction mismatch error.

**Comment by robbanp** [comment]
We're looking at this issue!
