### ISSUE TITLE
HTTP Basic: Access Denined

### ISSUE THREAD

**Issue by metinucar** [Mondido/MondidoWooCommerce#33]
Hi!

I'm getting a `Mondido Error: HTTP Basic: Access Denied` error on product edit view on WooCommerce, [see here](https://cl.ly/mHkx).

Besides I'm experiencing issues with payments and order statuses. Order status is not updated in WooCommerce even when customers successfully complete payment. As a result the order status is set to "Waiting for payment" and customers do not get e-mails that they are supposed to get when order status is set to "Processing", "Complete", etc.

I even made a few test orders in Test Mode but that did not help as well. It do not get any error on confirmation page but still the order status is set to "Waiting for payment".

Does anyone have any idea what might be happening here?

**Comment by metinucar** [comment]
@olegisk May I ask why you closed the issue?

**Comment by olegisk** [comment]
This issue has been fixed few releases ago

**Comment by metinucar** [comment]
I'm not working the project where I experienced this issue but it's good to know it's resolved.
