### ISSUE TITLE
WooCommerce fee added twice in order

### ISSUE THREAD

**Issue by jyourstone** [Mondido/MondidoWooCommerce#36]
## Using

- The latest master version of Mondido as of today
- WordPress 4.8.3
- WooCommerce 3.2.3
- A payment gateway fee plugin (seems to happen with all payment gateway fee plugins)

## What happens

When adding an extra fee for the payment Mondido Invoice, after the payment is complete the fee is added twice in the order. In Mondido the fee is only shown once, so it's only in WooCommerce the fee is shown twice.

## How to reproduce

1.  Download a payment gateway plugin, such as "WooCommerce Pay for Payment" or "WooCommerce Extra Charges To Payment Gateway".
2. Add a fee to Mondido Invoice
3. Pay with Mondido Invoice
4. When payment is completed, the fee shows twice in the order

## Additional info:

Commenting out the following line on row 238 in class-wc-gateway-mondido-abstract.php: $this->add_order_fee($fee, $order); "fixes" this particular problem, the fee is only shown once after doing so

**Comment by jyourstone** [comment]
Any comments on this?

**Comment by olegisk** [comment]
Hi @jyourstone 
This issue has been fixed here https://github.com/Mondido/MondidoWooCommerce/commit/828be29f78e93e984a7e003dbdd981c26749bdd2

**Comment by jyourstone** [comment]
Thank you!

**Comment by jyourstone** [comment]
Unfortunately the fee is still added twice after downloading the latest version.
@olegisk

**Comment by olegisk** [comment]
@jyourstone You are installed module from this branch? https://github.com/Mondido/MondidoWooCommerce/tree/mondido-checkout

**Comment by jyourstone** [comment]
@olegisk 
I was just about to comment that your fix actually works but I downloaded Master, not mondido-checkout.
What's the difference between those two?

**Comment by olegisk** [comment]
@jyourstone Currently latest changes in mondido-checkout branch. Please use it.

**Comment by jyourstone** [comment]
Ok thank you
