### ISSUE TITLE
Add "Loading..." messages before redirect to confirmation page

### ISSUE THREAD

**Issue by maokomioko** [Mondido/MondidoWooCommerce#39]
Time between 3ds completion and redirect to merchant's confirmation page take from 30 secs to a minute.

We need to display "Loading..." kind of messages one after another with a delay.
I.e. 
Right after the waiting starts, show this message:
"Please wait, your payment is being processed..."

Then 15 seconds after:
"Sorry for the wait, we are done soon."

And 30 seconds later (45 from the start) show the last message that would stay till the redirect:
"Almost there, just a few more seconds..."

**Comment by olegisk** [comment]
https://github.com/Mondido/MondidoWooCommerce/commit/91b0d2f95a9a576409d92e7c716838d7a38d7f48
