### ISSUE TITLE
Send order id to Mondido

### ISSUE THREAD

**Issue by jonathan-mondido** [Mondido/MondidoWooCommerce#40]
Can we send the generated Order ID to Mondido using this metadata update
{"store_order":{"id": "123123"}}

Then it will be rendered in the Mondido Admin view.

https://doc.mondido.com/api#transaction-update

**Comment by olegisk** [comment]
Done https://github.com/Mondido/MondidoWooCommerce/commit/b1b9ed1f5f00f8531265c08b39d905602b6bbe9e
