### ISSUE TITLE
Warning vid skapande av ny produkt.

### ISSUE THREAD

**Issue by hedqvist** [Mondido/MondidoWooCommerce#5]
Warning: Invalid argument supplied for foreach() in /public/wp-content/plugins/MondidoWooCommerce-master/index.php on line 74

**Comment by robbanp** [comment]
Thanks, we'll check it out!

**Comment by robbanp** [comment]
@hedqvist So if you don't have a API password, then you will get this error.
The fix will be deployed in the next version.
