### ISSUE TITLE
Is the plugin compatible with WooCommerce v3.5.x?

### ISSUE THREAD

**Issue by rasmuse** [Mondido/MondidoWooCommerce#59]
We are in the process of upgrading our WooCommerce store and are aiming for WooCommerce v3.5.8.

According to your plugin metadata (https://github.com/Mondido/MondidoWooCommerce/blob/master/woocommerce-gateway-mondido.php#L12) the plugin is tested up to WooCommerce v3.4.2 only.

Have you tested WooCommerce up to v3.5.8 (or higher)? Any reason to suspect it would not work with v3.5.x?

Thank you for your help.

**Comment by atimos** [comment]
Yes, the plugin is tested and works on 3.4.x 3.5.8 and 4.3.1

Will update "WC tested up to" in the next version
